# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import haki_ipc_pb2 as haki__ipc__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in haki_ipc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class HAKICoreStub(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    HAKICore is the single gRPC service that hosts the voice pipeline.
    One long-lived bidirectional stream per conversational session handles the
    entire interaction: audio upload, incremental transcription, LLM token
    streaming, TTS audio streaming, and out-of-band control events.

    Rationale for a single bidirectional RPC:
    • Avoids per-turn connection setup overhead that would blow the 300 ms
    first-audio budget (Req 3.1).
    • Allows the server to push partial transcripts and control events
    without waiting for a full TurnRequest.
    • Barge-in (CANCEL / BARGE_IN ControlEvent) can be sent at any point
    without racing a request/response boundary.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTurn = channel.stream_stream(
                '/haki.HAKICore/StreamTurn',
                request_serializer=haki__ipc__pb2.ClientMessage.SerializeToString,
                response_deserializer=haki__ipc__pb2.ServerMessage.FromString,
                _registered_method=True)


class HAKICoreServicer(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    HAKICore is the single gRPC service that hosts the voice pipeline.
    One long-lived bidirectional stream per conversational session handles the
    entire interaction: audio upload, incremental transcription, LLM token
    streaming, TTS audio streaming, and out-of-band control events.

    Rationale for a single bidirectional RPC:
    • Avoids per-turn connection setup overhead that would blow the 300 ms
    first-audio budget (Req 3.1).
    • Allows the server to push partial transcripts and control events
    without waiting for a full TurnRequest.
    • Barge-in (CANCEL / BARGE_IN ControlEvent) can be sent at any point
    without racing a request/response boundary.
    """

    def StreamTurn(self, request_iterator, context):
        """Main voice/command pipeline.
        The client streams ClientMessage frames; the server streams ServerMessage
        responses.  Both sides can send at any time — fully bidirectional.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HAKICoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTurn': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTurn,
                    request_deserializer=haki__ipc__pb2.ClientMessage.FromString,
                    response_serializer=haki__ipc__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'haki.HAKICore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('haki.HAKICore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HAKICore(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    HAKICore is the single gRPC service that hosts the voice pipeline.
    One long-lived bidirectional stream per conversational session handles the
    entire interaction: audio upload, incremental transcription, LLM token
    streaming, TTS audio streaming, and out-of-band control events.

    Rationale for a single bidirectional RPC:
    • Avoids per-turn connection setup overhead that would blow the 300 ms
    first-audio budget (Req 3.1).
    • Allows the server to push partial transcripts and control events
    without waiting for a full TurnRequest.
    • Barge-in (CANCEL / BARGE_IN ControlEvent) can be sent at any point
    without racing a request/response boundary.
    """

    @staticmethod
    def StreamTurn(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/haki.HAKICore/StreamTurn',
            haki__ipc__pb2.ClientMessage.SerializeToString,
            haki__ipc__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
