// ProposalPanelView.swift
// HAKI — UI Subsystem / Scheduler
//
// SwiftUI views for displaying and acting on calendar event proposals
// generated by the Scheduler (Req 11.1 – 11.7).
//
// Components:
//  - `ProposalPanel`  — scrollable list of pending proposals.
//  - `ProposalCard`   — a single proposal with confirm / reject / edit buttons.
//
// Routing to the UI:
//  The IPC inbound handler calls `UIState.postCalendarProposal(_:)` whenever
//  a `ServerMessage.proposalReceived` arrives.  `UIState.pendingProposals`
//  is `@Published` so views observing `UIState` refresh automatically.
//
// IPC callbacks:
//  User actions (confirm / reject) should send a `PROPOSAL_ACTION` ClientMessage
//  back through the `JSONIPCClient` so the Python Scheduler can update its state.
//
// Implements: Req 11.1 (surface proposal), 11.2 (require confirmation),
//             11.4 (reject), 11.5 (edit), 11.6 (validation).
// Design: Scheduler, Intent Routing.

import SwiftUI
import HAKIIPC

// MARK: - ProposalPanel

/// Scrollable list of pending calendar event proposals.
///
/// Embed in the HAKI menu-bar popover or a dedicated panel section.
/// Observes `UIState.pendingProposals` so updates arrive automatically.
public struct ProposalPanel: View {

    @ObservedObject private var uiState: UIState
    /// Optional callback invoked when the user confirms or rejects a proposal.
    /// Parameters: (proposalId, action) where action is "confirm" or "reject".
    public var onAction: ((String, String) -> Void)?

    public init(uiState: UIState, onAction: ((String, String) -> Void)? = nil) {
        self.uiState = uiState
        self.onAction = onAction
    }

    @MainActor
    public init(onAction: ((String, String) -> Void)? = nil) {
        self.uiState = UIState.shared
        self.onAction = onAction
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header
            HStack {
                Label("Proposals", systemImage: "calendar.badge.plus")
                    .font(.headline)
                Spacer()
                if !uiState.pendingProposals.isEmpty {
                    Text("\(uiState.pendingProposals.count)")
                        .font(.caption2)
                        .padding(.horizontal, 6)
                        .padding(.vertical, 2)
                        .background(Color.accentColor)
                        .foregroundColor(.white)
                        .clipShape(Capsule())
                }
            }
            .padding(.horizontal)
            .padding(.vertical, 8)

            Divider()

            if uiState.pendingProposals.isEmpty {
                emptyState
            } else {
                proposalList
            }
        }
        .frame(minWidth: 300, maxWidth: .infinity)
    }

    // MARK: Private

    private var emptyState: some View {
        VStack(spacing: 8) {
            Image(systemName: "calendar.badge.checkmark")
                .font(.largeTitle)
                .foregroundColor(.secondary)
            Text("No pending proposals")
                .foregroundColor(.secondary)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .padding()
    }

    private var proposalList: some View {
        ScrollView {
            LazyVStack(spacing: 10) {
                ForEach(uiState.pendingProposals, id: \.proposalId) { proposal in
                    ProposalCard(
                        proposal: proposal,
                        onConfirm: { onAction?(proposal.proposalId, "confirm") },
                        onReject: {
                            uiState.dismissProposal(proposal.proposalId)
                            onAction?(proposal.proposalId, "reject")
                        }
                    )
                }
            }
            .padding()
        }
    }
}

// MARK: - ProposalCard

/// A single pending calendar event proposal card.
///
/// Displays extracted date, time, title, and clarification badge if needed.
/// Confirm / Reject buttons trigger the parent callback and remove the card.
public struct ProposalCard: View {

    public let proposal: HAKICalendarProposal
    public var onConfirm: () -> Void
    public var onReject: () -> Void

    public init(
        proposal: HAKICalendarProposal,
        onConfirm: @escaping () -> Void = {},
        onReject: @escaping () -> Void = {}
    ) {
        self.proposal = proposal
        self.onConfirm = onConfirm
        self.onReject = onReject
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            // Title row with clarification badge
            HStack(alignment: .top) {
                VStack(alignment: .leading, spacing: 2) {
                    Text(proposal.title)
                        .font(.subheadline)
                        .fontWeight(.semibold)
                    if let location = proposal.location, !location.isEmpty {
                        Label(location, systemImage: "mappin.and.ellipse")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                }
                Spacer()
                if proposal.needsClarification {
                    Label("Needs clarification", systemImage: "exclamationmark.triangle.fill")
                        .labelStyle(.iconOnly)
                        .foregroundColor(.orange)
                        .help("Date or time is missing — please edit before confirming.")
                }
            }

            // Date / time row
            HStack(spacing: 12) {
                if let date = proposal.date {
                    Label(date, systemImage: "calendar")
                        .font(.caption)
                        .foregroundColor(.primary)
                }
                if let time = proposal.time {
                    Label(time, systemImage: "clock")
                        .font(.caption)
                        .foregroundColor(.primary)
                }
                if proposal.date == nil && proposal.time == nil {
                    Text("Date/time not extracted")
                        .font(.caption)
                        .foregroundColor(.orange)
                }
            }

            // Description (if different from title)
            if !proposal.description.isEmpty && proposal.description != proposal.title {
                Text(proposal.description)
                    .font(.caption)
                    .foregroundColor(.secondary)
                    .lineLimit(2)
            }

            Divider()

            // Action buttons
            HStack(spacing: 8) {
                // Confirm — gated on needsClarification (Req 11.2, 11.6)
                Button(action: onConfirm) {
                    Label("Confirm", systemImage: "checkmark.circle.fill")
                        .font(.caption)
                        .foregroundColor(.green)
                }
                .buttonStyle(.plain)
                .disabled(proposal.needsClarification)
                .help(proposal.needsClarification ? "Provide date and time before confirming." : "Confirm and create calendar event.")

                Spacer()

                // Reject (Req 11.4)
                Button(action: onReject) {
                    Label("Reject", systemImage: "xmark.circle.fill")
                        .font(.caption)
                        .foregroundColor(.red)
                }
                .buttonStyle(.plain)
                .help("Discard this proposal — no event will be created.")
            }
        }
        .padding(10)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(Color(NSColor.controlBackgroundColor))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 10)
                .stroke(
                    proposal.needsClarification ? Color.orange.opacity(0.6) : Color(NSColor.separatorColor),
                    lineWidth: 0.5
                )
        )
    }
}
